name: Build PLM Portable EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Build React
        run: npm run build

      - name: Build Portable EXE
        run: npx electron-builder --win portable

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PLM-System-Portable
          path: release/*.exe
